modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="the_fletching_table_mod"
version="1.3"
displayName="The Fletching Table Mod"
displayURL="https://www.hangel.dev/"
logoFile="logo.png"
credits="Nobody"
authors="The_Hangel"
description="This mod makes useful the unused Fletching Table block!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_fletching_table_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



